apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
# https://kubernetes.io/docs/concepts/storage/volume-snapshots/
metadata:
  name: my-snapshot1
  # this name will be used to link the PVC restore to this snapshot so that we can
  # run the PVC restore yaml to restore the deployment from this snapshot (this will be done with a new deployment mysql yaml that refers to the pvc-restore which
  # has a dataSource of mysnapshot-1 ).
spec:
  volumeSnapshotClassName: my-snapshotclass
  # this is the class name specified in the volumesnapshotclass yaml
  source:
    persistentVolumeClaimName: mysql-pv-claim
    # this is the same name from the pvc yaml
    # we are referencing the PVC name that is used for the deployment project in the
    # kube-manifests folder. This is the volume that we are taking a snapshot of.
    # ....the same volume claimed in that deployment.