apiVersion: v1
kind: PersistentVolumeClaim
# this PVC yaml looks very similar to the original deployment PVC except for the addition
# of the dataSource: in the spec:
# the dataSource refers to the name specified in the VolumeSnapshot.yaml (my-snapshot1)
# this is how this PVC is linked to the snapshot
metadata:
  name: pvc-restore
  # this name will be used in the new deployment mysql yaml file when we restore the snapshot to 
  # the deployment.
  # thus we must have a new mysql-deployment.yaml with this one change (the rest of it is the same)
  dataSource:
    name: my-snapshot1
    # this is the name of teh VolumeSnapshot.yaml snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi